// CHANGED: react-icons/fa -> lucide-react (FaBrain -> Brain), and the
// inline RISK_STYLES map is replaced by the shared Badge primitive
// (src/components/common/Badge.jsx) so risk styling lives in one place.
import { Brain } from "lucide-react";
import Badge from "./common/Badge";

// `insights` comes straight from the prediction endpoint — each item is
// {studentName, risk: "high"|"medium"|"low", note}. Falls back to sample
// copy so the panel still looks right before that endpoint exists.
const FALLBACK = [
  {
    studentName: "Neha Sharma",
    risk: "high",
    note: "Marks dropped 18% over two terms — recommend a one-on-one review.",
  },
  {
    studentName: "Amit Verma",
    risk: "medium",
    note: "Attendance below 75% this month; flag before the next exam cycle.",
  },
];

export default function AIInsightCard({ insights = FALLBACK, isLoading = false }) {
  return (
    <div className="relative bg-gradient-to-br from-[#0B1E45]/80 via-[#122a5c]/70 to-[#14306B]/60 backdrop-blur-2xl backdrop-saturate-150 border border-white/10 text-[#E7EEFF] rounded-2xl p-6 h-96 flex flex-col overflow-hidden shadow-[0_16px_48px_rgba(11,30,69,0.4)] ring-1 ring-[#38BDF8]/10">
      <div className="pointer-events-none absolute inset-x-0 top-0 h-px bg-gradient-to-r from-transparent via-[#38BDF8]/50 to-transparent" />
      <div className="pointer-events-none absolute -top-16 -right-16 w-56 h-56 rounded-full bg-[#38BDF8]/20 blur-3xl" />

      <div
        className="absolute -right-4 top-4 border-2 border-dashed border-[#38BDF8]/70 text-[#38BDF8] text-[10px] font-bold tracking-widest px-3 py-1 rounded rotate-6 select-none shadow-[0_0_16px_rgba(56,189,248,0.4)]"
        aria-hidden="true"
      >
        AI PICK
      </div>

      <div className="relative flex items-center gap-2 mb-5">
        <span className="w-8 h-8 rounded-lg bg-gradient-to-br from-[#38BDF8] to-[#1D4ED8] flex items-center justify-center shadow-[0_0_16px_rgba(56,189,248,0.5)]">
          <Brain className="text-white" size={14} />
        </span>
        <h2 className="text-lg font-semibold" style={{ fontFamily: "'Fraunces', serif" }}>
          Recommended Attention
        </h2>
      </div>

      {isLoading ? (
        <div className="flex-1 space-y-3">
          {[1, 2, 3].map((i) => (
            <div key={i} className="h-14 rounded-xl bg-white/5 animate-pulse" />
          ))}
        </div>
      ) : (
        <div className="relative flex-1 overflow-y-auto space-y-3 pr-1">
          {insights.map((item, i) => (
            <div
              key={i}
              className="bg-white/5 backdrop-blur-sm rounded-xl p-3.5 border border-white/10 hover:border-[#38BDF8]/30 hover:bg-white/8 transition-colors"
            >
              <div className="flex items-center justify-between mb-1">
                <p className="text-sm font-semibold">{item.studentName}</p>
                <Badge risk={item.risk}>{item.risk} risk</Badge>
              </div>
              <p className="text-xs text-[#AFC3EC] leading-relaxed">{item.note}</p>
            </div>
          ))}
        </div>
      )}

      <p className="relative text-[11px] text-[#8FA9DD] mt-4 pt-3 border-t border-white/10">
        Generated by the performance-prediction model · updates nightly
      </p>
    </div>
  );
}